firstdjango/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
#from inventory import views
from animeupload import views

from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm

from django.contrib.sitemaps.views import sitemap
from animeupload.sitemaps import *

mysitemaps = {
    'static': StaticViewSitemap(),
    'tag': TagSitemap(),
    'genre': GenreSitemap(),
    'show': ShowSitemap(),
}

ROBOTS_SITEMAP_VIEW_NAME = 'django.contrib.sitemaps.views.sitemap'

#url(r'^show/(?P<slug>\w+)/', views.show_detail, name='show_detail'),

urlpatterns = [
	url(r'^$',views.index, name='index'),
    url(r'^show/(?P<slug>[-\w]+)/', views.show_detail, name='show_detail'),
#    url(r'^admin/animeupload/genre/consolidate', views.consolidate, name="consolidate"),
    url(r'^admin/', admin.site.urls),
    url(r'^search/', views.search, name='search'),
    url(r'^rating_descriptions/', views.rating_descriptions, name='rating_descriptions'),
    url(r'^search_results/', views.search_results, name='search_results'),
#    url(r'^test/',views.test,name='test'),
    url(r'^ajax_search/',views.ajax_search,name='a_search'),
#    url(r'^tag_search/',views.tag_search,name='tag_search'),
#    url(r'^tag_results/',views.tag_results,name='tag_results'),
    url(r'^all_shows/',views.all_shows,name='all_shows'),
    url(r'^recommendations/',views.recommendations,name='recommendations'),
    url(r'^login/', auth_views.login, name="my_login"),
    url(r'^accounts/profile/',views.get_profile, name="my_profile"),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^accounts/createList/',views.createlist, name="create_list"),
    url(r'^accounts/deleteList/',views.deletelist, name="delete_list"),
    url(r'^accounts/removeShow/',views.removeshow, name="remove_show"),
    url(r'^accounts/addtoList/',views.addtolist, name="add_show"),
    url(r'^links/', views.links, name='links'),
    url(r'^tag/(?P<slug>[-\w]+)/', views.tag_detail, name='tag_detail'),
    url(r'^all_tags/',views.all_tags,name='all_tags'),
    url(r'^all_genres/',views.all_genres,name='all_genres'),
    url(r'^genre/(?P<slug>[-\w]+)/', views.genre_detail, name='genre_detail'),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': mysitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^robots\.txt$', include('robots.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#url(r'^(?P<show_name>)$')

animeupload/models.py
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from django.utils.text import slugify

LITE_TONE = NONE = 0
SUBBED = MODERATE_TONE = UNINTENTIONAL = CORPSE_LTE = LOW = ESRB_E = LIGHT = DAMN = UNDERWEAR = 1
DUBBED = DARK_TONE = MISCHIEVOUS = SILHOUETTE = MODERATE = ESRB_T = DEEP = CENCORED = 2
ULTA_DARK_TONE = MALICE_LTE = DISMEMBERED = HIGH = ESRB_M = SEX = FUCK = BUTT = 3
MALICE_HVY = EXTREME = ESRB_A = BARBIE_SMOOTH = 4
OUTINES = 5
NIPPLE = 6
FULL_FRONTAL = 7


standard_choices = (
	(NONE,"none"),
	(LOW,"low"),
	(MODERATE,"moderate"),
	(HIGH,"high"),
	(EXTREME,"extreme"),
)

# Create your models here.
class Series(models.Model):
	series_name = models.CharField(max_length=200)
	watch_order = models.CharField(max_length=500)

	def __str__(self):
		return self.series_name
	class Meta:
		verbose_name_plural = "series"

class Tag(models.Model):
	name=models.CharField(max_length=30, unique=True)
	description = models.CharField(max_length=150,null=True)
	slug = models.SlugField(max_length=30, null = True, blank =True)

	class Meta:
		ordering = ["name"]

	def __str__(self):
		return self.name

	def save(self, *args, **kwargs):
		self.name = self.name.lower()
		self.slug = slugify(self.name)
		super(Tag, self).save(*args, **kwargs)

	def get_absolute_url(self):
		return reverse('tag_detail', kwargs={'slug':self.slug})


class Genre(models.Model):
	name = models.CharField(max_length=30, unique=True)
	description = models.CharField(max_length=150,null=True)
	slug = models.SlugField(max_length=30, null = True, blank =True)

	class Meta:
		ordering = ["name"]

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('genre_detail', kwargs={'slug':self.slug})

	def save(self,*args,**kwargs):
		self.name = self.name.lower()
		self.slug = slugify(self.name)
		super(Genre, self).save(*args, **kwargs)

class Show(models.Model):

	n_choices= (
		(NONE,"none"),
		(UNDERWEAR,"underwear"),
		(CENCORED,"cencored"),
		(BUTT,"butt"),
		(BARBIE_SMOOTH,"barbie smooth"),
		(OUTINES,"outlined"),
		(NIPPLE,"nipple"),
		(FULL_FRONTAL,"full frontal"),
	)

	swares= (
		(NONE,"none"),
		(DAMN,"mild"),
		(CENCORED,"cencored"),
		(FUCK,"uncencored"),
	)
	osi_levels = (
		(NONE,"none"),
		(LIGHT,"light kissing"),
		(DEEP,"deep kissing/grope"),
		(SEX,"sex"),
	)

	osv_levels = (
		(NONE,"none"),
		(ESRB_E,"cartoon"),
		(ESRB_T,"blood"),
		(ESRB_M,"realistic"),
		(ESRB_A,"extreme"),
	)

	emotional_challenge = standard_choices

	mi_levels =(
		(NONE,"none"),
		(CORPSE_LTE,"unmarred dead"),
		(SILHOUETTE,"silhouetted dismemberment"),
		(DISMEMBERED,"dismemberment"),
	)
	gore_levels =standard_choices
		#none, lowblood, broken bone, cencored insideout, insideout

	fan_levels =standard_choices
	si_levels=(
		(NONE,"none"),
		(UNINTENTIONAL,"unintentional"),
		(MISCHIEVOUS,"mischievous"),
		(MALICE_LTE,"malicious(molestation)"),
		(MALICE_HVY,"extremley malicious(rape)"),
	)

	tone_levels=(
		(LITE_TONE,"light tone"),
		(MODERATE_TONE,"moderate tone"),
		(DARK_TONE,"dark tone"),
		(ULTA_DARK_TONE,"ultra dark tone"),
	)
	ma_levels = standard_choices

	image = models.FileField(default = "images/fnf/fnf.jpg", blank=True, upload_to='images/')

	english_title = models.CharField(max_length=200)
	japanese_title = models.CharField(max_length=200, null= True)
	description = models.TextField(max_length = 1000)

	length = models.IntegerField(null=True)

	series = models.ForeignKey(Series, null = True, blank = True, on_delete=models.SET_NULL)

#-------------------------------------------ratings-------------
	nudity = models.IntegerField(default = NONE, choices= n_choices)
	on_screen_intimacy = models.IntegerField(default = NONE, choices= osi_levels)
	sexual_intent = models.IntegerField(default = NONE, choices = si_levels)

	violence = models.IntegerField(default = NONE, choices= osv_levels)
	gore = models.IntegerField(default = NONE, choices= gore_levels)
	morbid_images = models.IntegerField(default = NONE, choices= mi_levels)

	feels = models.IntegerField(default = NONE, choices= emotional_challenge)
	profanity = models.IntegerField(default = NONE, choices= swares)
	moral_ambiguity = models.IntegerField(default = NONE, choices= ma_levels)

	fan_service = models.IntegerField(default = NONE, choices= fan_levels)
#---------------------------------------------------------------------------------
	tags = models.ManyToManyField(Tag, blank=True)
	genres = models.ManyToManyField(Genre, blank=True)

	modified_date = models.DateTimeField(auto_now=True, blank = True, null=True)
#---------------------------------------------------------------------------------
	slug = models.SlugField(max_length=30, null = True, blank =True)
#	funimation = models.IntegerField(defalt = NONE, choices = audio_choices)
#	crunchyroll =

	def __str__(self):
		return self.english_title

	class Meta:
		ordering = ["english_title"]

	def save(self, *args, **kwargs):
		self.english_title = self.english_title.lower()
		self.japanese_title = self.japanese_title.lower()
		self.slug = slugify(self.english_title)
		super(Show, self).save(*args, **kwargs)

	def get_absolute_url(self):
		return reverse('show_detail', kwargs={'slug':self.slug})

class TVShow(Show):
	total_episodes = models.IntegerField()
	total_seasons = models.IntegerField(default = 1)
	ongoing = models.BooleanField(default = False)

class Movie(Show):
	def __str__(self):
		return self.english_title

class Recommendation(models.Model):
	show = models.OneToOneField(Show, on_delete=models.CASCADE, null=True)
	recommended = models.CharField(max_length = 30)
	description = models.TextField(max_length = 1000)
	tldr = models.TextField(max_length = 160, null = True, blank= True)

class Showlist(models.Model):
	creator = models.ForeignKey( settings.AUTH_USER_MODEL)
	title = models.CharField(max_length = 30)
	shows =  models.ManyToManyField(Show, blank=True)
	likes = models.IntegerField(default = 0)

	class Meta:
		unique_together = ('creator', 'title',)

class Link(models.Model):
	name = models.CharField(max_length = 30)
	description = models.TextField(max_length = 1000)
	home_page = models.URLField()
	#-------------------------------------------get/make color field
	color_f = models.CharField(max_length = 30, default="black")
	background = models.CharField(max_length = 30,default = "white")
#	color2 = models.CharField(max_length = 30)

#	image = models.FileField( blank=True, upload_to='images/')

	youtube = models.URLField(blank = True)
	twitter = models.URLField(blank = True)
	facebook = models.URLField(blank = True)
	instagram = models.URLField(blank = True)
	tumblr = models.URLField(blank = True)
	pintrest = models.URLField(blank = True)

	google_plus = models.URLField(blank = True)

	twitch = models.URLField(blank = True)
#	class Meta:
#		abstract = True

	def __str__(self):
		return self.name

	def save(self, *args, **kwargs):
		self.name = self.name.lower()
		super(Link, self).save(*args, **kwargs)


class PrimaryLink(Link):
	INDENT = "0px"
	def __str__(self):
		return self.name

class SecondaryLink(Link):
	INDENT = "50px"
	parent_link = models.ForeignKey(PrimaryLink, null=True, related_name="parent_lnk")

	def __str__(self):
		return self.name

class WatchOption(models.Model):
	audio_choices = (
		(SUBBED,"english subbed"),
		(DUBBED,"english dubbed"),
	)
	show = models.ForeignKey(Show, on_delete = models.CASCADE)
	link = models.ForeignKey(Link, on_delete = models.CASCADE)
	free = models.BooleanField(default = False)
	audio = models.IntegerField(default = None, choices=audio_choices)

	class Meta:
		unique_together = (("show","link"),)

animeupload/forms.py
# forms.py
from django import forms
from .models import Series
from .models import Tag
from .models import Showlist
from .widgets import seriesWidget
from django.contrib.auth.models import User



class SeriesForm(forms.ModelForm):
	class Meta:
		model = Series
		fields = [ 'series_name', 'watch_order',]
#		exclude = ["watch_order"]
		widgets = {
			"watch_order" : seriesWidget(),
		}

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)
	class Meta:
		model = User
		fields = ['username', 'email', 'password']

class ShowListForm(forms.ModelForm):
	class Meta:
		model = Showlist
		fields = ('title',)
		added_show_id = forms.IntegerField(widget=forms.HiddenInput)

firstdjango/templates/animeupload/ajax_test.html
{% if results.count > 0 %}
	{% for show in results %}
		<div class="search_item">
			<a href = "/show/{{show.slug}}/">{{show.english_title}} </a><br><sub>{{show.japanese_title}}</sub>
			<br>
		</div> 
	{% endfor %}
{% elif empty%}

{% else %}
	<li>none found</li>
{% endif %}

firstdjango/templates/animeupload/all_shows.html
{% extends "base.html" %}

{% load staticfiles %}
{% load rating_tags %}

{% block seo_head %}
	<title>Show List| Anime Advisor</title>
		<meta name="description" content="{{meta_desc}}">
		<meta name="keywords" content="anime,rating,recommendations">
{% endblock %}

{% block content %}
	<div class="row">
	{% get_all_alp shows %}
	</div>
{% endblock %}

firstdjango/templates/animeupload/genre_detail.html
{% extends "animeupload/search_results.html" %}

{% block seo_head %}
	<title>{{genre.name}} | Anime Advisor</title>
		<meta name="description" content="{{genre.name}} genre description of and all shows with that genre">
		<meta name="keywords" content="anime,rating,recommendations,{{genre.name}}">
{% endblock %}

{% block pg_details %}
	<div class="col-sm-12" style="border-style:none none outset none">
		<h2>{{genre.name}}</h2>
		<h4>{{genre.description}}</h4>
	</div>
{% endblock %}

firstdjango/templates/animeupload/index.html
{% extends "wsidebar.html" %}

{% block main %}
	<div class="col-xs-9">
	<h2>Hello, and welcome to the Anime Advisor</h2>
	<p>
	 this site is here to help you find that new show while avoiding some of the stereotypical pit falls... filled with those notorious testicles. 
	unless you're into that, the Anime Advisor will let you search for whatever range of show you are looking for.
	</p>
	<p>
		as you may know, the term anime encompasses is a very wide range of shows. one might argue that it is similar to saying movies and there is a world of 
		difference between <a href = "http://www.imdb.com/title/tt0114369/?ref_=nv_sr_1" target="_blank">Se7en</a> and <a href="http://www.imdb.com/title/tt0472033/?ref_=fn_al_tt_1" target="_blank">9</a>.
	</p>
	<p>
	the main feature of this site is the rating system used on each show and the ability to search for different ranges on that system.
	if you are looking for a show that you want to start a younger sibling on you can filter out those shows with extreme nudity of violence.
	maybe you have a friend that is still sceptical of the anime medium. you can filter out the tags with overplayed tropes.
	If you are just looking for a show for yourself you can look up shows with a particular genre or any combonation of the above.
	</p>
	<p>
	with all of that being said enjoy the hunt for new shows and tell a friend about the site
	</p>
	<hr>

	<h3>LAST 50 SHOWS</h3>
	<ul>
		{% for show in shows|dictsort:"modified_date" %}
			{% if forloop.counter0 < 50%}
			<li>
				<a href = "{% url 'show_detail' show.slug %}">
					{{ show.english_title|title }}
				</a>
			</li>
			{% endif %}
		{% endfor %}
	</ul>
</div>
{% endblock %}

firstdjango/templates/animeupload/links.html
{% extends "wsidebar.html" %}

{% load rating_tags %}

{% block seo_head %}
	<title>Links | Anime Advisor</title>
		<meta name="description" content="links to other helpful anime resources">
		<meta name="keywords" content="anime,rating,recommendations,links">
{% endblock %}

{% block main %}
<div class="col-xs-9">
	<h1>
	</h1>
	<div class="link_container" style="border-style:solid; border-radius: 10px 0px;">

		{% for link in links%}
			{%mainlink_title link.name link.color_f link.background link.INDENT%}
			{%make_links link%}
			<p>{{link.description}}</p>
		{% endfor %}
<!--		<div class="link_title" style="background-color: white; color:purple; border-radius: 10px 0px 0px; font-size: 1.5em">
			Funimation
		</div>

			<div class= "link_body" style="display:table; width: 100%;">
			{%make_link "home"  "https://www.funimation.com/"%}
			{%make_link "youtube"  "https://www.funimation.com/"%}
			{%make_link "twitter"  "https://www.funimation.com/"%}
			{%make_link "facebook"  "https://www.funimation.com/"%}
			{%make_link "instagram"  "https://www.funimation.com/"%}
			{%make_link "yelp"  "https://www.funimation.com/"%}
<!--				<span class ="link" style="width:10%; display:table-cell"><a href= "https://www.funimation.com/" target="_blank">homepage</a></span>
				<span class ="link" style="width:10%; display:table-cell"><a href= "https://www.youtube.com/channel/UCVi2lI40LetxLBKn-rtWC3A" target="_blank">youtube</a></span>
				<span class ="link" style="width:10%; display:table-cell"><a href= "https://www.youtube.com/channel/UCVi2lI40LetxLBKn-rtWC3A" target="_blank">other</a></span>
				<span class ="link" style="width:10%; display:table-cell"><a href= "https://www.youtube.com/channel/UCVi2lI40LetxLBKn-rtWC3A" target="_blank">another other</a></span>

			</div>
		<p>
		odds are if you are watching an english dubbed show, it was dubbed by funimation.
		with their recent partnership with crunchyroll, they now have access to more subbed shows sooner.
		</p>
		<div class="link_secondary" style="background-color: white; color:purple; font-size: 1.5em; text-indent: 50px">
			dubble talk
		</div>
-->
	</div>
</div>
{% endblock %}

firstdjango/templates/animeupload/recommendations.html
{% extends "wsidebar.html" %}

{% block seo_head %}
	<title>Recommendations | Anime Advisor</title>
		<meta name="description" content="Recommendations on what anime to watch">
		<meta name="keywords" content="anime,rating,recommendations">
{% endblock %}

{% block main %}
<div class="col-xs-9">
	{% for rec in recommendations %}
		{%cycle '<div class = "row" style="display:flex;">' ''%}
			<div class="col-sm-6" style="border-style: groove; ">
				<h3>{{rec.recommended}}</h3>
				<h4><i>~{{rec.show.english_title}}~</i></h4>
				<hr>
				<img src = '{{ rec.show.image.url }}' class="img-thumbnail img-responsive" width = "50%" align = "right"><p>{{rec.description}}</p>
				{%if rec.tldr%}
				 <br>
				<div style="position:absolute; bottom:0;">
				<p><b><u>TL;DR:</u></b> {{rec.tldr}}</p>
				</div>
				{%endif%}
			</div>
			
		{%cycle '' '</div>'%}
		{% if forloop.last and  not forloop.counter|divisibleby:2%}
			<div class="col-sm-6" style="border-style: groove; ">
				<h3>palce for add</h3>
				<hr>
				<p>ad place</p>
			</div>
		</div>
		{% endif %}
	{% endfor %}

</div>
{% endblock %}



<!--		{%cycle '<div class = "row" style="display:flex; flex-wrap:wrap;">' ''%}
			<div class="col-sm-6" style="border-style: groove; display:flex; flex-direction:column;">
			-->

firstdjango/templates/animeupload/show_detail.html
{% extends "wsidebar.html" %}

{% load rating_tags %}

{%block seo_head%}
<title>{{show.english_title|title}} | Anime Advisor</title>
		<meta name="description" content="Details about {{show.english_title|title}} including: ratings, description and related tags/genres.">
		<meta name="keywords" content="{{show.english_title|title}} anime,rating,recommendations">
{%endblock%}

{% block main %}
<div class="col-xs-9">
	<div class = "row">
		<div class = "col-sm-3" >
			<img src = '{{ show.image.url }}'  width = "100%" align = "left">
			<a href="{% url 'all_shows' %}">Back to shows</a>     <!-------------------back to all shows------------------>
			{% if user.is_authenticated %}
			<div id="frm_list_add">
				<form method="POST" onsubmit =  "return checkNewList()" action="{%url 'add_show'%}">{% csrf_token %}
					<select id="slt_lists" name="lists">
						<option value="new list">new list</option>
						{%for list in showlists%}
							<option = value="{{list.title}}">{{list.title}}</option>
						{%endfor%}
					</select>
					<br>
					<input type = "submit" value ="&#10010; add to list">
					<input type = "hidden" name="added_show_id" value = "{{show.id}}">
				</form>
			</div>
			<div id ="new_list" class="hidden">
				<form method="POST" action="{%url 'create_list'%}">{% csrf_token %}
					<input type="text" name="title" placeholder="enter title">
					<input type ="submit" value="create" >
					<input type ="button" value="cancel" onclick="return hideNewList()">
					<input type ="hidden" name="added_show_id" value = "{{show.id}}">
				</form>
			</div>
			{% endif%}
		</div>
		<div class = "col-sm-9">
			<h3>{{ show.english_title|capfirst }}: </h3>
			<p>{{show.description}}</p>
			
			{%if show.episodes%}
			<h3> episodes: {{show.total_episodes}}</h3>
			<h3>ongoing:
				{%if show.ongoing %}
				yes
				{%else%}
				no
				{% endif %}
			</h3>
			{%endif%}
		</div>
	</div>

	{%if watch_options%}
	<div style="border-style: solid hidden; border-radius:5px;">
		<div class = "row" style = "margin:0;">
			<div class = "col-xs-3">
				<h4><u>service</u></h4>
			</div>
			<div class = "col-xs-3">
				<h4><u>free</u></h4>
			</div>
			<div class = "col-xs-6">
				<h4><u>english subtitles/dubbing</h4></u>
			</div>
		</div>
	{% endif %}
	{%for option in watch_options%}
		<div class = "row" style = "margin:0; border-bottom: {%if forloop.last %} hidden {%else%} dashed{%endif%};">
			<div class = "col-xs-3">
				<a href = "{{option.link.home_page}}" target="_blank"><h4>{{option.link}}</h4></a>
			</div>
			<div class = "col-xs-3">
				<h4>
			{%if option.free%}
				free
			{% else %}
				subscription fee
			{%endif%}
				</h4>
			</div>
			<div class = "col-xs-6">
				<h4>{{option.get_audio_display}}</h4>
			</div>
		</div>
	{% endfor %}
	{%if watch_options%}
	</div>
	{%endif%}
	
	<div class="row" >
	<div class = "col-sm-12">

		<table style="border-collapse: separate;">
		<tr>
			<th><h3>runtime:</h3></th>
			<td valign="bottom"><h4>
			{% if show.length == None %}
				N/A
			{% else %}
				{{show.length}} min
			{% endif %}
			</h4></td>
		</tr>

		<tr>
			<th><h3>tags:</h3></th>
		<form id="search_form" action = "/search_results/" method = "POST">{% csrf_token %}

			{% for tag in show.tags.all%}
				<th style="padding:0px 5px;"><div class="tag_box" > <a href = "{%url 'tag_detail' tag.slug%}">{{tag}}</a></div></th>
			{% endfor %}
		</tr>

		<tr>
			<th><h3>genres:</h3></th>
			{% for genre in show.genres.all%}
				<th style="padding:0px 5px;"><div class="genre_box" ><a href = "{%url 'genre_detail' genre.slug%}">{{genre}}</a> </div></th>
			{% endfor %}
			
		</form>
		</tr>
		</table>

		<h3>Series Viewing Order</h3>

		<div style="display: flex;">
			{% display_series show.series show.id%}
		</div>
		<br>

	</div>
	</div>

	<div class = "row">

		<div class ="col-sm-12">
			<div class = "show_param">
				<div id="sex_ratings" class = "rating_box bg_lightpurple">
	<!--------------------------------------nudity rating------------------------------------------------->
					<h3>nudity : {{show.get_nudity_display}}</h3>
					<div style = "width: 100%">
						{% display_rating show.nudity show.n_choices%}
					</div>
	<!--------------------------------------fan service rating------------------------------------------------------>				
						<h3>On Fan Service: {{show.get_fan_service_display}}</h3>
						<div style = "width: 100%">
							{% display_rating show.fan_service show.fan_levels%}
						</div>
					
					
					
					<a data-toggle="collapse" href="#sex_ratings_extras" class="collapsible">See more ratings</a>
					<div id = "sex_ratings_extras" class = "collapse">
						<hr>
		<!--------------------------------------intimacy rating------------------------------------------------------>
						<h3>On Screen Intimacy: {{show.get_on_screen_intimacy_display}}</h3>
						<div style = "width: 100%">
							{% display_rating show.on_screen_intimacy show.osi_levels%}
						</div>

		<!--------------------------------------intent rating------------------------------------------------------>
						<h3>On Sexual intent: {{show.get_sexual_intent_display}}</h3>
						<div style = "width: 100%">
							{% display_rating show.sexual_intent show.si_levels%}
						</div>
					</div>		
				</div>

				<div id = "violence_ratings" class="rating_box bg_lightred">
	<!--=========================================================================================================>
	<!--------------------------------------violence rating------------------------------------------------->
					<h3>On Screen Violence: {{show.get_violence_display}}</h3>
					<div style = "width: 100%">
						{% display_rating show.violence show.osv_levels %}
					</div>
					<a data-toggle="collapse" href="#violence_ratings_extras"class="collapsible">See more ratings</a>

					<div id="violence_ratings_extras" class = "collapse">
					<hr>
	<!--------------------------------------gore rating------------------------------------------------->
						<h3>On Screen Gore: {{show.get_gore_display}}</h3>
						<div style = "width: 100%">
							{% display_rating show.gore show.gore_levels %}
						</div>

			<!--------------------------------------morbid rating------------------------------------------------->
						<h3>morbid images: {{show.get_morbid_images_display}}</h3>
						<div style = "width: 100%">
							{% display_rating show.morbid_images show.mi_levels %}
						</div>
					</div>
				</div>


				<div id = "other_ratings" class = "rating_box bg_lightblue">
	<!--=========================================================================================================>
		<!--------------------------------------feels rating------------------------------------------------->
					<h3>emotional challange: {{show.get_feels_display}}</h3>
					<div style = "width: 100%">
						{% display_rating show.feels show.emotional_challenge %}
					</div>
					<a data-toggle="collapse" href="#other_ratings_extras"class="collapsible">See more ratings</a>

					<div id = "other_ratings_extras" class = "collapse">
					<hr>
		<!--------------------------------------feels rating------------------------------------------------->
						<h3>Profanity: {{show.get_profanity_display}}</h3>
						<div style = "width: 100%">
							{% display_rating show.profanity show.swares %}
						</div>

			<!--------------------------------------feels rating------------------------------------------------->
						<h3>moral ambiguity: {{show.get_moral_ambiguity_display}}</h3>
						<div style = "width: 100%">
							{% display_rating show.moral_ambiguity show.ma_levels %}
						</div>
					</div>
				</div>
			</div>
		</div>

	</div>
</div>

<script>
function showNewList()
{
	var nl_form = document.getElementById("new_list");
	var ls_form = document.getElementById("frm_list_add");
	
//	nl_form.style.display = "inline";
	if(nl_form.classList.contains("hidden"))
	{
		nl_form.classList.remove("hidden");
		ls_form.classList.add("hidden");
	}
}
function hideNewList()
{
	var nl_form = document.getElementById("new_list");
	var ls_form = document.getElementById("frm_list_add");
	//nl_form.style.display = "none";
	nl_form.classList.add("hidden");
	if(ls_form.classList.contains("hidden"))
	{
		ls_form.classList.remove("hidden");
	}
}

function checkNewList()
{
	var slt_lists = document.getElementById("slt_lists");
	var curr_value = slt_lists.value;
	if(curr_value == "new list")
	{
		showNewList();
		return false;
	}
	return true;
}
</script>
{% endblock %}

firstdjango/templates/animeupload/tag_results.html
{% extends "animeupload/search_results.html" %}

{% block seo_head %}
	<title>{{tag.name}} | Anime Advisor</title>
		<meta name="description" content="{{tag.name}} tag description and all shows with that tag ">
		<meta name="keywords" content="anime,rating,recommendations,{{tag.name}}">
{% endblock %}

{% block pg_details %}
	<div class="col-sm-12" style="border-style:none none outset none">
		<h2>{{tag.name}}</h2>
		<h4>{{tag.description}}</h4>
	</div>
{% endblock %}